import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/providers/authContext';
import Header from '@/components/Header/Header';

const NotoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-NotoSansJp',
});

export const metadata: Metadata = {
  title: '図書管理アプリ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSansJp.variable} font-NotoSansJp`}>
        <AuthProvider>
          <Header />
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
